// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"o37k64vum9","name":"PiSensorDataCRUD","description":"","endpoint":"https://o37k64vum9.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/PiSensorData","/PiSensorData/123"]}],
    'aws_cognito_identity_pool_id': 'eu-west-2:da90675d-5526-41a0-baba-640f3711bf63',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'pisensorclient-hosting-mobilehub-1516835929',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1a3bftooitg18.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'eu-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"pisensorclient-mobilehub-1516835929-PiSensorData","attributes":[{"name":"ID","type":"S"},{"name":"TimeStamp","type":"N"}],"indexes":[],"region":"eu-west-2","hashKey":"ID","rangeKey":"TimeStamp"}],
    'aws_mobile_analytics_app_id': '43a4ea3dc8d644e9822a9549f89daf5f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5e0eb26b-90d4-4a76-b785-63c46957d5d3',
    'aws_project_name': 'Pi_Sensor_Client',
    'aws_project_region': 'eu-west-2',
    'aws_resource_bucket_name': 'pisensorclient-deployments-mobilehub-1516835929',
    'aws_resource_name_prefix': 'pisensorclient-mobilehub-1516835929',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-2_CwdeuJyd0',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '55bj913qh0h0n270prlm3s9jg4',
}

export default awsmobile;
